spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true