spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

resilience4j:
  retry:
    instances:
      dbRetry:
        maxAttempts: 3
        waitDuration: 100ms
        retryExceptions:
          - org.springframework.dao.TransientDataAccessException
          - java.sql.SQLTransientException
