spring:
  r2dbc:
    url: r2dbc:h2:mem:///maindb;DB_CLOSE_DELAY=-1
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    #        generate-ddl: true
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true